# Generated by Django 5.0.3 on 2024-03-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_project_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
