# Generated by Django 5.0.3 on 2024-03-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_alter_project_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='projects',
            field=models.ManyToManyField(related_name='tags', to='Project.project'),
        ),
        migrations.DeleteModel(
            name='ProjectTag',
        ),
    ]
