# Generated by Django 5.0.3 on 2024-03-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='reason_for_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
