# Generated by Django 5.0.3 on 2024-03-25 20:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_project_created_at_project_updated_at'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='rating_count',
            new_name='total_rating_count',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='total_rating',
            new_name='total_rating_value',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
